### ISSUE TITLE
Implementarlo con un ESP32

### ISSUE THREAD

**Issue by kr4fty** [ronibandini/reggaetonBeGone#1]
Primero que nada me pareció muy bueno el proyecto. Ya hace un tiempo buscaba formas de bloquear el parlante molesto del vecino.

Rastreando temas relacionados había encontrado este vídeo, que actua directamente sobre la wifi, expulsando al cliente que esta enviando el sonido al parlante desde Internet

[Como apagar la musica del vecino](https://www.youtube.com/watch?v=gyItgM_Qkj4)

Mi idea seria ver como funciona tu código e tratar de implementarlo sobre un ESP32 con una antena exterior.

Por ahora seguimos esperando el código para ver como funciona tu script

**Comment by ronibandini** [comment]
Exitos con eso. Cualquier avance podés anunciarlo acá
