### ISSUE TITLE
Hc-05?

### ISSUE THREAD

**Issue by elelfo** [ronibandini/reggaetonBeGone#2]
No se si es mucha locura la idea de incorporar varios módulos hc-05 a la rapsberry pi para hacer un seudo ataque ddos al bl del altavoz.

si es así podría probar con su código a ver que tal funciona.

_________________________________________________________________________________________________________

I don't know if the idea of incorporating several HC-05 modules into the Rapsberry Pi to make a pseudo DDOS attack on the speaker's BL is too crazy.

If so, I could try your code to see how it works.

**Comment by ronibandini** [comment]
There are several steps for setup but it is possible and you can also use longer cables and place the HC-05 as an antenna.
