### ISSUE TITLE
Firing problem

### ISSUE THREAD

**Issue by AlivE-git** [ronibandini/reggaetonBeGone#4]
Method 1:
`Can't connect RFCOMM socket: Device or resource busy`
Method 2:
`Can't create socket: Operation not permitted`

**Comment by rubenleon** [comment]
Hello, 

Method 2:
It was solved with sudo

`sudo python3 reggaetonBeGone.py`

**Comment by rubenleon** [comment]
> Method 1: `Can't connect RFCOMM socket: Device or resource busy` Method 2: `Can't create socket: Operation not permitted`

Hello,

Method 2:
It was solved with sudo

sudo python3 reggaetonBeGone.py

**Comment by AlivE-git** [comment]
Now it works, but there is a new error:
`Can't connect: Host is down`
I'm testing on wireless headphones connected to a PC. I can see them via bluetoothctl.
![image](https://github.com/ronibandini/reggaetonBeGone/assets/12865205/d6ef88de-6d55-4ff8-beac-430f274ffb23)

**Comment by Sig2018** [comment]
Same here with Method 1: Can't connect RFCOMM socket: Device or resource busy
Did you find why?

**Comment by AlivE-git** [comment]
The first method does not work the same with sudo.
I'll wait for my neighbor to turn on the music and test the second one :)

**Comment by Sig2018** [comment]
I tried second method and didn't work either.
Message says:
no response first 
and second line "Connection reset by peer"
