### ISSUE TITLE
Problem with ID of audio device

### ISSUE THREAD

**Issue by IkerS25** [ronibandini/reggaetonBeGone#8]
Hi, I can start the project perfectly, but it gives me the following error when I press the button. No matter what number you enter, the same error always appears, this is with version 2.0, in version 1.0 it did not happen.

This is what I see on the screen, I have tried everything possible, starting Jack Server, Pulse Audio, etc.

**ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.iec958.0:CARD=0,AES0=6,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2 CARD 0}
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_asym.c:105:(_snd_pcm_asym_open) capture slave is not defined
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1838
2 --> USB PnP Sound Device: Audio (hw:3,0):
Type the id of the audio device you want to use: 
0
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1838
2 --> USB PnP Sound Device: Audio (hw:3,0)**

**Comment by ronibandini** [comment]
Did you select the correct device in selectedDeviceId? Are you sure that the mic works with RBG version 1.0? In my setup an external USB sound board is used.

**Comment by IkerS25** [comment]
> Did you select the correct device in selectedDeviceId? Are you sure that the mic works with RBG version 1.0? In my setup an external USB sound board is used.

Apparently, this error is due to running it with root, I have installed all the dependencies without root in a virtual environment and the detection works fine but the attack does not work, I imagine it is because I do not have root permissions, any idea what I can do?

**Comment by ronibandini** [comment]
I won't bet in that cause. It could also be related to the MIC being used. If you don't have an external board, you can start over following the original instructions.
